[2024-06-13T09:50:05.463+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T09:50:05.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T09:48:46.903981+00:00 [queued]>
[2024-06-13T09:50:05.487+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T09:48:46.903981+00:00 [queued]>
[2024-06-13T09:50:05.488+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T09:50:05.499+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 09:48:46.903981+00:00
[2024-06-13T09:50:05.508+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7352) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T09:50:05.509+0000] {standard_task_runner.py:63} INFO - Started process 7377 to run task
[2024-06-13T09:50:05.509+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T09:48:46.903981+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpu2ghgxoq']
[2024-06-13T09:50:05.510+0000] {standard_task_runner.py:91} INFO - Job 400: Subtask test_model_task
[2024-06-13T09:50:05.539+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T09:48:46.903981+00:00 [running]> on host 33b4ab31339c
[2024-06-13T09:50:05.599+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T09:48:46.903981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T09:48:46.903981+00:00'
[2024-06-13T09:50:05.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T09:50:06.288+0000] {logging_mixin.py:188} INFO -  1/17 ━━━━━━━━━━━━━━━━━━━━ 3s 228ms/step
[2024-06-13T09:50:06.339+0000] {logging_mixin.py:188} INFO - 15/17 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step  
[2024-06-13T09:50:06.504+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T09:50:06.505+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[2024-06-13T09:50:06.894+0000] {warnings.py:112} WARNING - /opt/***/dags/demo_***.py:315: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data1['Dự đoán'] = y_test_predict  # thêm dữ liệu

[2024-06-13T09:50:07.115+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T09:50:07.116+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:50:07.122+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T09:48:46.903981+00:00, execution_date=20240613T094846, start_date=20240613T095005, end_date=20240613T095007
[2024-06-13T09:50:07.170+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T09:50:07.199+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:50:07.201+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
