[2024-06-13T01:59:34.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T01:59:34.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T01:59:34.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task scheduled__2024-06-12T00:00:00+00:00 [queued]>
[2024-06-13T01:59:35.000+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T01:59:35.146+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-12 00:00:00+00:00
[2024-06-13T01:59:35.297+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1036) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T01:59:35.295+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'scheduled__2024-06-12T00:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmp2wr5p1jr']
[2024-06-13T01:59:35.310+0000] {standard_task_runner.py:91} INFO - Job 297: Subtask test_model_task
[2024-06-13T01:59:35.301+0000] {standard_task_runner.py:63} INFO - Started process 1054 to run task
[2024-06-13T01:59:35.532+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task scheduled__2024-06-12T00:00:00+00:00 [running]> on host 33b4ab31339c
[2024-06-13T01:59:35.749+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-12T00:00:00+00:00'
[2024-06-13T01:59:35.785+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T01:59:40.380+0000] {logging_mixin.py:188} INFO -  1/82 ━━━━━━━━━━━━━━━━━━━━ 2:13 2s/step
[2024-06-13T01:59:40.432+0000] {logging_mixin.py:188} INFO -  4/82 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
[2024-06-13T01:59:40.492+0000] {logging_mixin.py:188} INFO -  7/82 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
[2024-06-13T01:59:40.545+0000] {logging_mixin.py:188} INFO - 10/82 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
[2024-06-13T01:59:40.607+0000] {logging_mixin.py:188} INFO - 13/82 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
[2024-06-13T01:59:40.661+0000] {logging_mixin.py:188} INFO - 15/82 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step
[2024-06-13T01:59:40.714+0000] {logging_mixin.py:188} INFO - 17/82 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
[2024-06-13T01:59:40.785+0000] {logging_mixin.py:188} INFO - 21/82 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step
[2024-06-13T01:59:40.856+0000] {logging_mixin.py:188} INFO - 24/82 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
[2024-06-13T01:59:40.914+0000] {logging_mixin.py:188} INFO - 27/82 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
[2024-06-13T01:59:40.987+0000] {logging_mixin.py:188} INFO - 30/82 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
[2024-06-13T01:59:41.044+0000] {logging_mixin.py:188} INFO - 33/82 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step
[2024-06-13T01:59:41.107+0000] {logging_mixin.py:188} INFO - 37/82 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[2024-06-13T01:59:41.166+0000] {logging_mixin.py:188} INFO - 41/82 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[2024-06-13T01:59:41.222+0000] {logging_mixin.py:188} INFO - 45/82 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[2024-06-13T01:59:41.277+0000] {logging_mixin.py:188} INFO - 49/82 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[2024-06-13T01:59:41.339+0000] {logging_mixin.py:188} INFO - 53/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T01:59:41.396+0000] {logging_mixin.py:188} INFO - 57/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T01:59:41.452+0000] {logging_mixin.py:188} INFO - 61/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T01:59:41.508+0000] {logging_mixin.py:188} INFO - 65/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T01:59:41.565+0000] {logging_mixin.py:188} INFO - 69/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T01:59:41.623+0000] {logging_mixin.py:188} INFO - 73/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T01:59:41.686+0000] {logging_mixin.py:188} INFO - 77/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T01:59:41.740+0000] {logging_mixin.py:188} INFO - 81/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T01:59:43.054+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[2024-06-13T01:59:43.058+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 4s 33ms/step
[2024-06-13T01:59:43.472+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T01:59:43.474+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 275, in test_model
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
                                                  ~~~~~~~~~~~~^^^
IndexError: tuple index out of range
[2024-06-13T01:59:43.511+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=test_model_task, run_id=scheduled__2024-06-12T00:00:00+00:00, execution_date=20240612T000000, start_date=20240613T015934, end_date=20240613T015943
[2024-06-13T01:59:43.551+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 297 for task test_model_task (tuple index out of range; 1054)
[2024-06-13T01:59:43.696+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T01:59:43.775+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T01:59:43.784+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
