[2024-06-11T17:53:42.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T17:53:42.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.describe_data_task manual__2024-06-11T17:53:30.150785+00:00 [queued]>
[2024-06-11T17:53:42.565+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.describe_data_task manual__2024-06-11T17:53:30.150785+00:00 [queued]>
[2024-06-11T17:53:42.566+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-11T17:53:42.578+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): describe_data_task> on 2024-06-11 17:53:30.150785+00:00
[2024-06-11T17:53:42.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2286) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T17:53:42.586+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'describe_data_task', 'manual__2024-06-11T17:53:30.150785+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmp07u2z6kl']
[2024-06-11T17:53:42.587+0000] {standard_task_runner.py:63} INFO - Started process 2304 to run task
[2024-06-11T17:53:42.587+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask describe_data_task
[2024-06-11T17:53:42.621+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.describe_data_task manual__2024-06-11T17:53:30.150785+00:00 [running]> on host ad0cd89ef011
[2024-06-11T17:53:42.680+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='describe_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T17:53:30.150785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T17:53:30.150785+00:00'
[2024-06-11T17:53:42.682+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T17:53:42.689+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T17:53:42.690+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 48, in describe_data
    info = df.info()
           ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'
[2024-06-11T17:53:42.701+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=describe_data_task, run_id=manual__2024-06-11T17:53:30.150785+00:00, execution_date=20240611T175330, start_date=20240611T175342, end_date=20240611T175342
[2024-06-11T17:53:42.711+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task describe_data_task ('NoneType' object has no attribute 'info'; 2304)
[2024-06-11T17:53:42.722+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T17:53:42.745+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T17:53:42.749+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
