[2024-06-13T02:32:32.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T02:32:32.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:27:53.651829+00:00 [queued]>
[2024-06-13T02:32:32.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:27:53.651829+00:00 [queued]>
[2024-06-13T02:32:32.727+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T02:32:32.814+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 02:27:53.651829+00:00
[2024-06-13T02:32:32.849+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3393) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T02:32:32.855+0000] {standard_task_runner.py:63} INFO - Started process 3418 to run task
[2024-06-13T02:32:32.855+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T02:27:53.651829+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmp5g4purwg']
[2024-06-13T02:32:32.857+0000] {standard_task_runner.py:91} INFO - Job 313: Subtask test_model_task
[2024-06-13T02:32:32.965+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:27:53.651829+00:00 [running]> on host 33b4ab31339c
[2024-06-13T02:32:33.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T02:27:53.651829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T02:27:53.651829+00:00'
[2024-06-13T02:32:33.252+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T02:32:35.508+0000] {logging_mixin.py:188} INFO -  1/82 ━━━━━━━━━━━━━━━━━━━━ 1:20 995ms/step
[2024-06-13T02:32:35.598+0000] {logging_mixin.py:188} INFO -  2/82 ━━━━━━━━━━━━━━━━━━━━ 7s 91ms/step   
[2024-06-13T02:32:35.749+0000] {logging_mixin.py:188} INFO -  3/82 ━━━━━━━━━━━━━━━━━━━━ 9s 121ms/step
[2024-06-13T02:32:35.800+0000] {logging_mixin.py:188} INFO -  7/82 ━━━━━━━━━━━━━━━━━━━━ 3s 49ms/step 
[2024-06-13T02:32:35.854+0000] {logging_mixin.py:188} INFO - 11/82 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step
[2024-06-13T02:32:35.926+0000] {logging_mixin.py:188} INFO - 14/82 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step
[2024-06-13T02:32:35.975+0000] {logging_mixin.py:188} INFO - 17/82 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step
[2024-06-13T02:32:36.028+0000] {logging_mixin.py:188} INFO - 20/82 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step
[2024-06-13T02:32:36.095+0000] {logging_mixin.py:188} INFO - 24/82 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step
[2024-06-13T02:32:36.146+0000] {logging_mixin.py:188} INFO - 27/82 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step
[2024-06-13T02:32:36.210+0000] {logging_mixin.py:188} INFO - 31/82 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step
[2024-06-13T02:32:36.271+0000] {logging_mixin.py:188} INFO - 35/82 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step
[2024-06-13T02:32:36.332+0000] {logging_mixin.py:188} INFO - 39/82 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[2024-06-13T02:32:36.385+0000] {logging_mixin.py:188} INFO - 43/82 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[2024-06-13T02:32:36.441+0000] {logging_mixin.py:188} INFO - 47/82 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
[2024-06-13T02:32:36.502+0000] {logging_mixin.py:188} INFO - 52/82 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[2024-06-13T02:32:36.554+0000] {logging_mixin.py:188} INFO - 56/82 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[2024-06-13T02:32:36.615+0000] {logging_mixin.py:188} INFO - 61/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T02:32:36.677+0000] {logging_mixin.py:188} INFO - 66/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T02:32:36.736+0000] {logging_mixin.py:188} INFO - 71/82 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[2024-06-13T02:32:36.786+0000] {logging_mixin.py:188} INFO - 75/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T02:32:36.844+0000] {logging_mixin.py:188} INFO - 80/82 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
[2024-06-13T02:32:37.605+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[2024-06-13T02:32:37.675+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 3s 27ms/step
[2024-06-13T02:32:37.897+0000] {logging_mixin.py:188} INFO - x_test shape before reshaping: (0,)
[2024-06-13T02:32:37.971+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T02:32:37.974+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 282, in test_model
    raise ValueError("x_test is empty, check the loop that populates x_test")
ValueError: x_test is empty, check the loop that populates x_test
[2024-06-13T02:32:38.013+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T02:27:53.651829+00:00, execution_date=20240613T022753, start_date=20240613T023232, end_date=20240613T023238
[2024-06-13T02:32:38.058+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 313 for task test_model_task (x_test is empty, check the loop that populates x_test; 3418)
[2024-06-13T02:32:38.217+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T02:32:38.296+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T02:32:38.312+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
