[2024-06-13T02:54:08.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T02:54:08.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:49:23.401716+00:00 [queued]>
[2024-06-13T02:54:08.943+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:49:23.401716+00:00 [queued]>
[2024-06-13T02:54:08.944+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T02:54:08.992+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 02:49:23.401716+00:00
[2024-06-13T02:54:09.027+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5703) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T02:54:09.032+0000] {standard_task_runner.py:63} INFO - Started process 5721 to run task
[2024-06-13T02:54:09.031+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T02:49:23.401716+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmposlu7ks3']
[2024-06-13T02:54:09.034+0000] {standard_task_runner.py:91} INFO - Job 330: Subtask test_model_task
[2024-06-13T02:54:09.126+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:49:23.401716+00:00 [running]> on host 33b4ab31339c
[2024-06-13T02:54:09.337+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T02:49:23.401716+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T02:49:23.401716+00:00'
[2024-06-13T02:54:09.340+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T02:54:11.492+0000] {logging_mixin.py:188} INFO -  1/82 ━━━━━━━━━━━━━━━━━━━━ 1:06 825ms/step
[2024-06-13T02:54:11.542+0000] {logging_mixin.py:188} INFO -  5/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step   
[2024-06-13T02:54:11.602+0000] {logging_mixin.py:188} INFO - 10/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:54:11.654+0000] {logging_mixin.py:188} INFO - 14/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:11.709+0000] {logging_mixin.py:188} INFO - 18/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:11.766+0000] {logging_mixin.py:188} INFO - 22/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:11.839+0000] {logging_mixin.py:188} INFO - 23/82 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[2024-06-13T02:54:11.891+0000] {logging_mixin.py:188} INFO - 27/82 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[2024-06-13T02:54:11.944+0000] {logging_mixin.py:188} INFO - 31/82 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[2024-06-13T02:54:11.996+0000] {logging_mixin.py:188} INFO - 36/82 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[2024-06-13T02:54:12.054+0000] {logging_mixin.py:188} INFO - 42/82 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
[2024-06-13T02:54:12.109+0000] {logging_mixin.py:188} INFO - 47/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:12.164+0000] {logging_mixin.py:188} INFO - 52/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:12.215+0000] {logging_mixin.py:188} INFO - 57/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:12.267+0000] {logging_mixin.py:188} INFO - 62/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:12.320+0000] {logging_mixin.py:188} INFO - 67/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:54:12.372+0000] {logging_mixin.py:188} INFO - 72/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:54:12.430+0000] {logging_mixin.py:188} INFO - 78/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:54:13.208+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[2024-06-13T02:54:13.210+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step
[2024-06-13T02:54:13.333+0000] {logging_mixin.py:188} INFO - [[67200.]
 [67800.]
 [67200.]
 [66500.]
 [67000.]]
[2024-06-13T02:54:13.335+0000] {logging_mixin.py:188} INFO - [[67200.]
 [67800.]
 [67200.]
 [66500.]
 [67000.]]
[2024-06-13T02:54:13.338+0000] {logging_mixin.py:188} INFO - [[0.4280183 ]
 [0.43505808]
 [0.4280183 ]
 [0.41980523]
 [0.42567171]]
[2024-06-13T02:54:13.340+0000] {logging_mixin.py:188} INFO - Shape of test data before loop: (5, 1)
[2024-06-13T02:54:13.341+0000] {logging_mixin.py:188} INFO - Shape of sc_test: (5, 1)
[2024-06-13T02:54:13.342+0000] {logging_mixin.py:188} INFO - x_test shape before reshaping: (0,)
[2024-06-13T02:54:13.344+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T02:54:13.346+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 288, in test_model
    raise ValueError("x_test is empty, check the loop that populates x_test")
ValueError: x_test is empty, check the loop that populates x_test
[2024-06-13T02:54:13.376+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T02:49:23.401716+00:00, execution_date=20240613T024923, start_date=20240613T025408, end_date=20240613T025413
[2024-06-13T02:54:13.410+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 330 for task test_model_task (x_test is empty, check the loop that populates x_test; 5721)
[2024-06-13T02:54:13.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T02:54:13.525+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T02:54:13.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
