[2024-06-13T16:12:15.458+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T16:12:15.489+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T16:11:00.985266+00:00 [queued]>
[2024-06-13T16:12:15.519+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T16:11:00.985266+00:00 [queued]>
[2024-06-13T16:12:15.520+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T16:12:15.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 16:11:00.985266+00:00
[2024-06-13T16:12:15.572+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=29872) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T16:12:15.574+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T16:11:00.985266+00:00', '--job-id', '552', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpck8g1orr']
[2024-06-13T16:12:15.574+0000] {standard_task_runner.py:63} INFO - Started process 29890 to run task
[2024-06-13T16:12:15.575+0000] {standard_task_runner.py:91} INFO - Job 552: Subtask test_model_task
[2024-06-13T16:12:15.610+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T16:11:00.985266+00:00 [running]> on host 33b4ab31339c
[2024-06-13T16:12:15.694+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T16:11:00.985266+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T16:11:00.985266+00:00'
[2024-06-13T16:12:15.696+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T16:12:16.523+0000] {logging_mixin.py:188} INFO -  1/17 ━━━━━━━━━━━━━━━━━━━━ 5s 356ms/step
[2024-06-13T16:12:16.575+0000] {logging_mixin.py:188} INFO - 11/17 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step  
[2024-06-13T16:12:16.778+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[2024-06-13T16:12:16.779+0000] {logging_mixin.py:188} INFO - 17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step
[2024-06-13T16:12:16.801+0000] {logging_mixin.py:188} INFO - 521
[2024-06-13T16:12:16.856+0000] {warnings.py:112} WARNING - /opt/***/dags/demo_***.py:261: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data1['predict'] = y_test_predict  # thêm dữ liệu

[2024-06-13T16:12:17.257+0000] {logging_mixin.py:188} INFO - Độ phù hợp tập test: 0.9308831262725152
[2024-06-13T16:12:17.258+0000] {logging_mixin.py:188} INFO - Sai số tuyệt đối trung bình trên tập test (VNĐ): 782.0079324616123
[2024-06-13T16:12:17.258+0000] {logging_mixin.py:188} INFO - Phần trăm sai số tuyệt đối trung bình tập test: 0.01134845987222354
[2024-06-13T16:12:17.312+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
[2024-06-13T16:12:17.313+0000] {logging_mixin.py:188} INFO - 1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
[2024-06-13T16:12:17.323+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-13T16:12:17.324+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T16:12:17.331+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T16:11:00.985266+00:00, execution_date=20240613T161100, start_date=20240613T161215, end_date=20240613T161217
[2024-06-13T16:12:17.356+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T16:12:17.375+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-13T16:12:17.378+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
