[2024-06-13T02:42:09.320+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T02:42:09.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:37:31.598833+00:00 [queued]>
[2024-06-13T02:42:09.395+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:37:31.598833+00:00 [queued]>
[2024-06-13T02:42:09.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-13T02:42:09.428+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_model_task> on 2024-06-13 02:37:31.598833+00:00
[2024-06-13T02:42:09.449+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T02:42:09.453+0000] {standard_task_runner.py:63} INFO - Started process 4518 to run task
[2024-06-13T02:42:09.453+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_prediction', 'test_model_task', 'manual__2024-06-13T02:37:31.598833+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/demo_***.py', '--cfg-path', '/tmp/tmpcu0y1ka6']
[2024-06-13T02:42:09.456+0000] {standard_task_runner.py:91} INFO - Job 321: Subtask test_model_task
[2024-06-13T02:42:09.547+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_prediction.test_model_task manual__2024-06-13T02:37:31.598833+00:00 [running]> on host 33b4ab31339c
[2024-06-13T02:42:09.806+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nguyen Khoa Doan' AIRFLOW_CTX_DAG_ID='stock_prediction' AIRFLOW_CTX_TASK_ID='test_model_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T02:37:31.598833+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T02:37:31.598833+00:00'
[2024-06-13T02:42:09.810+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T02:42:14.793+0000] {logging_mixin.py:188} INFO -  1/82 ━━━━━━━━━━━━━━━━━━━━ 1:15 926ms/step
[2024-06-13T02:42:14.843+0000] {logging_mixin.py:188} INFO -  5/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step   
[2024-06-13T02:42:14.893+0000] {logging_mixin.py:188} INFO -  9/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:42:14.946+0000] {logging_mixin.py:188} INFO - 14/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:42:14.999+0000] {logging_mixin.py:188} INFO - 19/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.056+0000] {logging_mixin.py:188} INFO - 25/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.114+0000] {logging_mixin.py:188} INFO - 31/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.170+0000] {logging_mixin.py:188} INFO - 36/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.223+0000] {logging_mixin.py:188} INFO - 40/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.282+0000] {logging_mixin.py:188} INFO - 45/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.343+0000] {logging_mixin.py:188} INFO - 50/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.395+0000] {logging_mixin.py:188} INFO - 54/82 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step
[2024-06-13T02:42:15.451+0000] {logging_mixin.py:188} INFO - 58/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:42:15.508+0000] {logging_mixin.py:188} INFO - 61/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:42:15.566+0000] {logging_mixin.py:188} INFO - 64/82 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
[2024-06-13T02:42:15.624+0000] {logging_mixin.py:188} INFO - 67/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:42:15.686+0000] {logging_mixin.py:188} INFO - 70/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:42:15.739+0000] {logging_mixin.py:188} INFO - 74/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:42:15.794+0000] {logging_mixin.py:188} INFO - 78/82 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
[2024-06-13T02:42:16.523+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[2024-06-13T02:42:16.525+0000] {logging_mixin.py:188} INFO - 82/82 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step
[2024-06-13T02:42:16.652+0000] {logging_mixin.py:188} INFO - Shape of test data before loop: (5, 1)
[2024-06-13T02:42:16.653+0000] {logging_mixin.py:188} INFO - Shape of sc_test: (5, 1)
[2024-06-13T02:42:16.654+0000] {logging_mixin.py:188} INFO - x_test shape before reshaping: (0,)
[2024-06-13T02:42:16.655+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T02:42:16.657+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo_airflow.py", line 285, in test_model
    raise ValueError("x_test is empty, check the loop that populates x_test")
ValueError: x_test is empty, check the loop that populates x_test
[2024-06-13T02:42:16.681+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_prediction, task_id=test_model_task, run_id=manual__2024-06-13T02:37:31.598833+00:00, execution_date=20240613T023731, start_date=20240613T024209, end_date=20240613T024216
[2024-06-13T02:42:16.708+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 321 for task test_model_task (x_test is empty, check the loop that populates x_test; 4518)
[2024-06-13T02:42:16.750+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T02:42:16.793+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T02:42:16.800+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
